### ISSUE TITLE
Safety of Event::source

### ISSUE THREAD

**Issue by antoniusf** [cloudhead/popol#3]
Hi,

I was considering using your library for one of my projects and skimmed over the source, in particular the two unsafe blocks, and I was a bit confused by the use of `from_raw_fd` in `Event::source`. The [documentation for this function](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html#tymethod.from_raw_fd) says that "This function is also unsafe as the primitives currently returned have the contract that they are the sole owner of the file descriptor they are wrapping." It seems to me that `Event::source` cannot uphold this guarantee, since

(a) One place for these file descriptors to come from is `Sources::register`, which uses `as_raw_fd` internally, which in turn does not consume the object passed to it.
(b) `Event::source` takes `&self`, which means that it can be called multiple times on the same fd.

I'm not sure if I understand everything right (maybe all this isn't a problem), so I was curious what your thoughts on this were. Thanks!

**Comment by cloudhead** [comment]
Hey, thanks for your note. So let's try to understand what's going on here: it basically says that the objects returned from this, for example `File` or `net::TcpStream` assume that they are the sole owners of the underlying file descriptor. This makes sense, because if they are dropped, the file gets closed. So if you have two of them and one gets dropped, you'll get an i/o error on the other, trying to use a closed file.

Now, this *is* safe for certain types of objects that wrap a file descriptor. We know this because for eg. these functions aren't unsafe: https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.try_clone, and neither is https://doc.rust-lang.org/std/fs/struct.File.html#method.try_clone, so it *is* possible to have copies of a file descriptor.

However, these functions duplicate the fd in a specific way, and calling `from_raw_fd` isn't the same thing. So, I think the safest thing to do here is actually to mark this function as `unsafe`. I actually don't use it in any of my projects, and it's not used within popol, so it's really not a big deal for it to be marked unsafe.

**Comment by antoniusf** [comment]
Thanks for your response! To be honest, I think I read the documentation a bit differently than you did: for example, it explicitly mentions that re-using an fd could lead to memory unsafety, not just i/o errors? And, as you have said, the `try_clone` methods actually duplicate the file descriptor by creating an entirely new fd that refers to the same socket/file, and then wrapping it again. ([At least under unix, as far as I can tell.](https://github.com/rust-lang/rust/blob/937f629535f38c655267f1ed21ce6830f592f5df/library/std/src/sys/unix/fd.rs#L271))

I agree that marking `Event::source` as unsafe is probably the safe thing to do here, but I also don't want to force you into changing your library. It's nice to hear though that this function isn't essential to using it.

**Comment by cloudhead** [comment]
I've made the change here: https://github.com/cloudhead/popol/commit/aa0f7dc09b7cc13d1f0b186dc9b5c4a32f96ff3a

It's available as part of `0.4.0`

Have a nice day!

**Comment by antoniusf** [comment]
Awesome, thank you! And thanks for making this library.
