### ISSUE TITLE
Proposal: unify wait() and wait_timeout()

### ISSUE THREAD

**Issue by danielparks** [cloudhead/popol#4]
Having separate `wait()` and `wait_timeout()` functions is (mildly) inconvenient in code where the timeout is optional. It would be nice to have a unified function that takes `Option<Duration>`, for example:

```rust
pub fn poll(
    &mut self,
    events: &mut Events<K>,
    timeout: Option<time::Duration>,
) -> Result<(), io::Error> {
    // . . .
}
```

`wait()` and `wait_timeout()` could be depreciated and implemented with the unified function. (I called it `poll` since reusing the name `wait` would break existing code.)

I’m happy to write the code (and take whatever feedback you provide).

**Comment by cloudhead** [comment]
I understand why you'd want this, but I try hard to avoid functions that take `Option`, because in the `None` case it doesn't read well, eg. `self.wait(events, None)` doesn't give you any indication of what `None` is supposed to be.

One alternative is to define a type with a `From<time::Duration>` and `From<Option<time::Duration>` instance, which would look like:

```rust
enum Timeout {
  After(time::Duration),
  Never
}
```
What do you think?

**Comment by danielparks** [comment]
Sure, I‘m definitely in favor of clarity. I actually noticed that exact issue in some other code just the other day. Would you like me to prepare a PR?
